// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiVn9BBlpY0rvxUvhVzkKXEpco8uWz3Ns',
    appId: '1:883480335045:web:bcb6cd64da13de3787d6ac',
    messagingSenderId: '883480335045',
    projectId: 'todolist-c7f75',
    authDomain: 'todolist-c7f75.firebaseapp.com',
    storageBucket: 'todolist-c7f75.appspot.com',
    measurementId: 'G-Y8T7377656',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_CNnIlp9B1oCIsC2rCWSkhpW0ArIfzUM',
    appId: '1:883480335045:android:f803d7478a8eaba087d6ac',
    messagingSenderId: '883480335045',
    projectId: 'todolist-c7f75',
    storageBucket: 'todolist-c7f75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAA41oW9C4KBN_45UB73VEfX9SWk-usZM',
    appId: '1:883480335045:ios:65a38b11b32c23b687d6ac',
    messagingSenderId: '883480335045',
    projectId: 'todolist-c7f75',
    storageBucket: 'todolist-c7f75.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAA41oW9C4KBN_45UB73VEfX9SWk-usZM',
    appId: '1:883480335045:ios:65a38b11b32c23b687d6ac',
    messagingSenderId: '883480335045',
    projectId: 'todolist-c7f75',
    storageBucket: 'todolist-c7f75.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiVn9BBlpY0rvxUvhVzkKXEpco8uWz3Ns',
    appId: '1:883480335045:web:13b1abf47117c13d87d6ac',
    messagingSenderId: '883480335045',
    projectId: 'todolist-c7f75',
    authDomain: 'todolist-c7f75.firebaseapp.com',
    storageBucket: 'todolist-c7f75.appspot.com',
    measurementId: 'G-B0EQ4JM3BX',
  );
}
